## USB port
port: /dev/sensor_imu


##### Calibration ####
### accelerometer
accel_x_min: -258.30
accel_x_max: 257.57
accel_y_min: -259.16
accel_y_max: 251.46
accel_z_min: -271.12
accel_z_max: 266.72

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [-46.3001, -256.789, -504.924]
magn_ellipsoid_transform: [[0.964879, 0.0167609, 0.0107535], [0.0167609, 0.951714, 0.0186343], [0.0107535, 0.0186343, 0.982687]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: -0.01
gyro_average_offset_y: -0.02
gyro_average_offset_z: 0.0
