## USB port
port: /dev/sensor_imu


##### Calibration ####
### accelerometer
accel_x_min: -255.13
accel_x_max: 259.40
accel_y_min: -259.16
accel_y_max: 257.45
accel_z_min: -296.02
accel_z_max: 290.28

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [-395.756, -654.700, -1454.55]
magn_ellipsoid_transform: [[0.865345, -0.141758, -0.132587], [-0.141758, 0.849848, -0.149078], [-0.132587, -0.149078, 0.771140]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: -0.01
gyro_average_offset_y: -0.02
gyro_average_offset_z: 0.0
