## USB port
port: /dev/sensor_imu


##### Calibration ####
### accelerometer
accel_x_min: -255.86
accel_x_max: 256.59
accel_y_min: -256.35
accel_y_max: 262.21
accel_z_min: -260.13
accel_z_max: 266.97

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [-27.2034, -380.696, -741.934]
magn_ellipsoid_transform: [[0.973235, 0.0221867, -0.00221778], [0.0221867, 0.963429, 0.0320596], [-0.00221778, 0.0320596, 0.094949577]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: -0.01
gyro_average_offset_y: 0.0
gyro_average_offset_z: 0.0
