uPokeDB vehicle.moos TRACKED_FEATURE="x=72, y=-78, label=a, size=5, color=red"
uPokeDB vehicle.moos TRACKED_FEATURE="x=69, y=-68, label=b, size=5, color=red"
uPokeDB vehicle.moos TRACKED_FEATURE="x=41, y=-80, label=c, size=5, color=red"
uPokeDB vehicle.moos TRACKED_FEATURE="x=45, y=-89, label=d, size=5, color=red"
uPokeDB vehicle.moos TRACKED_FEATURE="x=57, y=-129, label=f, size=5, color=red"
uPokeDB vehicle.moos TRACKED_FEATURE="x=65, y=-149, label=g, size=5, color=green"
uPokeDB vehicle.moos TRACKED_FEATURE="x=61, y=-138, label=h, size=5, color=green"
uPokeDB vehicle.moos TRACKED_FEATURE="x=94, y=-126, label=i, size=5, color=red"
